#5 Make API Key Handling more robust
dogeared/ctfd-account-hook pull request #6
Opened 2023-10-05 00:46 UTC by Monoradioactivo

2023-10-05 14:55 UTC, dogeared requested changes
Thanks so much for this! It's like 99% there. I added a few comments and requests.

2023-10-05 14:55 UTC, dogeared commented on src/main/java/dev/dogeared/ctfdaccounthook/model/ApiKey.java
> +  private UUID id;
Let's add another String here for `description`.

2023-10-05 14:55 UTC, dogeared commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyAuthenticationServiceImpl.java
> +    ApiKey storedKey = apiKeyService.validateApiKey(apiKey);
wondering if we need a separate `ApiKeyService`? Maybe this should all be in `ApiKeyAuthenticationService`. Maybe not... just thinking out loud...

2023-10-05 14:55 UTC, dogeared commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyServiceImpl.java
> +      return null; // This can be changed to throw an exception if you want to be more explicit
Yes, let's throw a `BadCredentialException` here and it will be caught in the calling method.

2023-10-05 14:55 UTC, dogeared commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyServiceImpl.java
> +  private Date calculateExpirationDate() {
Is this used anywhere?

2023-10-05 14:55 UTC, dogeared commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyAuthenticationServiceImpl.java
> +    BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
Can this be added as a private field to the class so it's just available and not instantiated each time?

2023-10-05 14:55 UTC, dogeared commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyServiceImpl.java
> +    BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
Where's the salt? Wouldn't that be an additional field in the repository?

2023-10-05 17:50 UTC, Monoradioactivo commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyServiceImpl.java
> +  private Date calculateExpirationDate() {
Yes, it is. It is used in the generateApiKey() method to set the expiration date for a newly generated API key

2023-10-05 17:57 UTC, Monoradioactivo commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyServiceImpl.java
> +    BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
With BCrypt, when we use encoder.encode(rawApiKey) it creates a unique salt, mixes it with our API key, and then gives us a combined result. That's why we don't see or store the salt separately since it's already in there. So, every time we hash something, BCrypt handles all the behind-the-scenes work for us.

2023-10-05 17:57 UTC, Monoradioactivo commented
I have updated the PR

2023-10-05 18:02 UTC, Monoradioactivo commented on src/main/java/dev/dogeared/ctfdaccounthook/model/ApiKey.java
> +  private UUID id;
Done!

2023-10-05 18:02 UTC, Monoradioactivo commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyServiceImpl.java
> +      return null; // This can be changed to throw an exception if you want to be more explicit
Done!

2023-10-06 11:00 UTC, dogeared commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyAuthenticationServiceImpl.java
> +    ApiKey storedKey = apiKeyService.validateApiKey(apiKey);
I like your thinking here. Let's keep it as is.

2023-10-06 11:14 UTC, dogeared commented
I'm getting test failures locally - maybe because of the change from returning `null` to throwing the `BadCredentialsException`? I'll be able to look at it more tomorrow.

2023-10-06 11:16 UTC, dogeared requested changes

2023-10-06 11:16 UTC, dogeared commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyServiceImpl.java
> +  private Date calculateExpirationDate() {
Ah. I see. Maybe we can pass in a param for days rather than hardcode to 30 days?

2023-10-06 11:16 UTC, dogeared commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyAuthenticationServiceImpl.java
> +    BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
I don't see this change? Still shows on line 39 for me locally...

2023-10-06 11:23 UTC, dogeared commented
Ah, yes - the test failures are related to the new Exception handling. for `testValidateRevokedApiKey`, for instance, you can change it to:

```
    BadCredentialsException bce = assertThrows(BadCredentialsException.class,
          () -> apiKeyService.validateApiKey("someHashedKey"), "Expected throw, but didn't");
    assertThat(bce.getMessage(), is("Invalid or expired API Key"));
```

and then the test will pass again.

2023-10-06 20:35 UTC, Monoradioactivo commented on src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyServiceImpl.java
> +  private Date calculateExpirationDate() {
Done! Please review

2023-10-06 20:41 UTC, Monoradioactivo commented
I've made the necessary adjustments to the tests and taken your feedback into account. Could you please take another look?

2023-10-08 04:17 UTC, dogeared commented
Hey @Monoradioactivo - thanks again for this. However, I think there's a fundamental issue with this approach. Are you available for a zoom call sometime this week?

The TL;DR is that the request for the API endpoint should always be the _unhashed_ raw value. However, the `ApiKeyService.validate` method is expecting a _hash_ value.

2023-10-09 01:56 UTC, Monoradioactivo commented
> Hey @Monoradioactivo - thanks again for this. However, I think there's a fundamental issue with this approach. Are you available for a zoom call sometime this week?
> 
> The TL;DR is that the request for the API endpoint should always be the _unhashed_ raw value. However, the `ApiKeyService.validate` method is expecting a _hash_ value.

Thanks for pointing that out. I see the discrepancy you're mentioning between the raw API key expected by the endpoint and the hashed value expected by the ApiKeyService.validate method.

I agree that the API endpoint should receive the raw, unhashed value for better usability. I can modify the validateApiKey method to expect the raw key, hash it internally, and then perform the necessary validations against the stored hashed key in the database. This way, we maintain the security of storing only hashed keys while ensuring the API is user-friendly.

2023-10-10 21:27 UTC, Monoradioactivo commented
@dogeared  The PR already have your changes too! Thank you.

2023-10-11 11:32 UTC, merged

2023-10-11 11:33 UTC, dogeared commented
resolves #1